services:
  todo-app:
    build: .
    container_name: "todo-app"
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=todo_app
      - MONGODB_USERNAME=moben
      - MONGODB_PASSWORD=moben
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=moben
      - MONGO_INITDB_ROOT_PASSWORD=moben
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=moben
      - ME_CONFIG_MONGODB_ADMINPASSWORD=moben
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_PASSWORD=moben
      - ME_CONFIG_BASICAUTH_USERNAME=moben
    depends_on:
      - mongodb
volumes:
  mongo: {}