spring:
  data:
    mongodb:
      username: moben
      password: moben
      host: localhost
      port: 27017
      database: todo_app
      authentication-database: admin
  graphql:
     graphiql:
       enabled: true
server:
  port: 8088
